<?php

/**
 * @file
 * Contains shibauth8.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function shibauth8_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  // @todo - add help.
}

function shibauth8_user_delete(Drupal\Core\Entity\EntityInterface $entity) {
  /** @var \Drupal\Core\Database\Connection $db */
  $db = \Drupal::service('database');
  $db->delete('shib_authmap')
    ->condition('uid', $entity->id())
    ->execute();
}

/**
 * Implements hook_form_alter().
 */
function shibauth8_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if ($form_id != 'user_login_form') {
    return;
  }

  // Add Shibboleth link to form.
  $form['shibboleth_login_block'] = [
    '#weight' => -10,
    '#markup' => '<div class="shibboleth-login">'
      . shibauth8_get_login_link()
      . '</div>',
  ];

}

/**
 * Get the Shibboleth login link.
 *
 * @return \Drupal\Core\GeneratedLink
 */
function shibauth8_get_login_link() {

  $config = \Drupal::config('shibauth8.shibbolethsettings');
  $url = $config->get('shibboleth_login_handler_url');
  $link_text = $config->get('shibboleth_login_link_text');

  $config = \Drupal::config('shibauth8.advancedsettings');
  $redirect = $config->get('url_redirect_login');

  if ($redirect) {
    $redirect = Url::fromUserInput($redirect, ['absolute' => TRUE])->toString();
  }
  else {
    // Not set, use current page.
    $redirect = \Drupal\Core\Url::fromRoute('<current>', [], ['absolute' => TRUE])->toString();
  }
  $options = [
    'query' => [
      'target' => $redirect,
    ],
  ];

  if (parse_url($url, PHP_URL_HOST)) {
    $url = Url::fromUri($url, $options);
  }
  else {
    $url = Url::fromUserInput($url, $options);
  }

  return Link::fromTextAndUrl($link_text, $url)->toString();

}

/**
 * Get the Shibboleth logout link.
 *
 * @return \Drupal\Core\GeneratedLink
 */
function shibauth8_get_logout_link() {
  return Link::createFromRoute(t('Shibboleth Logout'), 'shibauth8.logout_controller_logout')
    ->toString();
}
